server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5434/estoque
spring.datasource.username=estoque
spring.datasource.password=estoque123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
